import type { Metadata } from "next";
import { Providers } from "./provider";
import { NextIntlClientProvider } from "next-intl";
import localFont from "next/font/local";
import { AppShell } from "@/components/generalComponents/AppShell";
import { cookies } from "next/headers";
import { SUPPORTED_LOCALES, type Locale } from "@/shared/utils/localeCookie";
import "./globals.css";
const onest = localFont({
  src: [
    {
      path: "./fonts/onest/Onest-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/onest/Onest-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/onest/Onest-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Goalize",
  description: "Generated by create next app",
};

async function getLocale(): Promise<Locale> {
  const cookieStore = await cookies();
  const cultureCookie = cookieStore.get(".AspNetCore.Culture")?.value;
  if (cultureCookie) {
    const match = cultureCookie.match(/c=([^|;]+)/);
    const extracted = match?.[1] as Locale | undefined;
    if (extracted && SUPPORTED_LOCALES.includes(extracted)) {
      return extracted;
    }
  }
  return "en";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} className={onest.variable}>
      <body>
        <NextIntlClientProvider>
          <Providers>
            <AppShell>{children}</AppShell>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
