import type { Metadata } from "next";
import Header from "@/components/generalComponents/Header";
import { Providers } from "./provider";
import { NextIntlClientProvider } from "next-intl";
import Footer from "@/components/generalComponents/Footer";
import localFont from "next/font/local";
import GlobalErrorHandler from "@/components/generalComponents/GlobalErrorHandler";
import "./globals.css";
const onest = localFont({
  src: [
    {
      path: "./fonts/onest/Onest-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/onest/Onest-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/onest/Onest-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Goalise",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={onest.variable}>
      <body>
        <NextIntlClientProvider>
          <Providers>
            <Header />
            <GlobalErrorHandler />

            <main className="container">{children}</main>

            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
